#pragma once
#include <exception>
#include <iostream>
#include <memory>
#include <set>
#include <utility>
#include <vector>
#include <limits>
#include <algorithm>
#include <string>
#define GLM_FORCE_RADIANS
#define GLM_FORCE_DEPTH_ZERO_TO_ONE
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <vulkan/vulkan.hpp>
#include <vulkan/vulkan_raii.hpp>
#include <GLFW/glfw3.h>